version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t db-migration-api .
      - docker tag db-migration-api:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo '[{"name":"db-migration-api","imageUri":"'$REPOSITORY_URI:latest'"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
