version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 311380684673.dkr.ecr.us-east-2.amazonaws.com/db-migration-api-cicd:latest
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t db-migration-api .
      - docker tag db-migration-api:latest 311380684673.dkr.ecr.us-east-2.amazonaws.com/db-migration-api-cicd:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 311380684673.dkr.ecr.us-east-2.amazonaws.com/db-migration-api-cicd:latest
      - echo '[{"name":"db-migration-api","imageUri":"'311380684673.dkr.ecr.us-east-2.amazonaws.com/db-migration-api-cicd:latest'"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
